name: face_recognition
description: This is the Face Recognition Flutter app which can be running on both Android & iOS platform.
author: Phương Nguyễn (ngtrphuong@gmail.com)
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  camera: ^0.8.1
  cupertino_icons: ^1.0.2
  google_ml_vision: ^0.0.6
  flutter:
    sdk: flutter
  image_picker: ^0.6.0
  image: ^3.0.2
  tflite_flutter: ^0.8.0
  path_provider: ^2.0.2
  bitmap: ^0.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
